sudo: false
language: node_js
os:
  - osx
osx_image: xcode8.2
dist: trusty
cache:
  directories:
    - node_modules
node_js:
  - "6.1"
script:
  - npm run lint && npm test
notifications:
  slack:
    secure: bDwO2uce5JAZvjrvWj4+/+yEXJAIK4O0RcgUWvZ2IMbi7Q9I89Mw40JmkLWL6x2gWZwxr8+FoLtErJA7RVrsfImjrX+NmMyAB7AydLdrBJtkLozNnuacnhcnBRyp1gGCa1ymxCEXGbgC6onAD3kiJJhggr70T+2lu3IuJYXENhc=
env:
  - CXX=g++-4.8 NODE_ENV=test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
